// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM4GxfkvuTjuJ5SKenbqYxRiyfOVXIHbA',
    appId: '1:555649675743:web:1eaf45925da73ef474146a',
    messagingSenderId: '555649675743',
    projectId: 'emergency-52955',
    authDomain: 'emergency-52955.firebaseapp.com',
    storageBucket: 'emergency-52955.appspot.com',
    measurementId: 'G-6G7J5NLLPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO0t1OCgHm2_VnlxOHe61ooeAe9x4yqZw',
    appId: '1:555649675743:android:388af02375d01cac74146a',
    messagingSenderId: '555649675743',
    projectId: 'emergency-52955',
    storageBucket: 'emergency-52955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1QD86PTGMiBSOYtKFI37s79Sxh5mZBEM',
    appId: '1:555649675743:ios:3c9e8d01c410543a74146a',
    messagingSenderId: '555649675743',
    projectId: 'emergency-52955',
    storageBucket: 'emergency-52955.appspot.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1QD86PTGMiBSOYtKFI37s79Sxh5mZBEM',
    appId: '1:555649675743:ios:bd3577310a3641cc74146a',
    messagingSenderId: '555649675743',
    projectId: 'emergency-52955',
    storageBucket: 'emergency-52955.appspot.com',
    iosBundleId: 'com.example.hello.RunnerTests',
  );
}
